resolver: clash-1.6.1.yaml

packages:
    - clash-shake
    - '.'

extra-deps:
  - retroclash-lib-0.1.2
  - retroclash-sim-0.1.1
  - clashilator-0.1.2

  - monoidal-containers-0.6.0.1

nix:
  path: [nixpkgs=channel:nixos-22.05]
  packages: [pkg-config SDL2]
